version: "3"
services:
  backend:
    build:
      context: ./springboot_app
    ports:
      - "8080:8080"
  frontend:
     build:
       context: ./react_app
     ports:
      - "8082:8082"
     depends_on:
      - backend
